version: '3'
services:
  db:
    image: mongo:4.4.3
    restart: always
    # environment:
    #   # mongodb client connection
    #   MONGO_INITDB_DATABASE: docker_rails_dev
    #   MONGO_INITDB_ROOT_USERNAME: mongoroot
    #   MONGO_INITDB_ROOT_PASSWORD: mongosecret
    ports:
      - "27018:27017"
    volumes:
      - "docker_mongodbdata:/var/lib/mongo/data"
    
  web:
    build: .
    image: rails-mongo-dockerized
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ".:/rails-mongo-dockerized"
      - "docker_bundler_gems:/usr/local/bundle"
    ports:
      - "3005:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      RAILS_ENV: development

volumes:
  docker_mongodbdata:
  docker_bundler_gems: